# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# This workflow will install Deno then run Deno lint and test.
# For more information see: https://github.com/denoland/setup-deno

name: Sukt 前端Dashboard CI

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v2

      - name: 安装npm包  #进入项目目录----发布项目
        run: yarn install --cwd sukt.core.react && cd sukt.core.react && yarn build
      - name: 打印打包文件夹
        run: ls /sukt.core.react
      - name: copy nginx.conf and Dockerfile to build
        run: ls /sukt.core.react
      - name: 打印build文件夹目录
        run: ls /sukt.core.react
